Develop netcore fix task1-2
Liza123-321/iTechLab18-lizaveta.kaliaha pull request #10
Opened 2018-08-10 11:41 UTC by Liza123-321

2018-08-14 13:33 UTC, DenomikoN requested changes
Стало больше замечаний, если есть вопросы - пиши

2018-08-14 13:33 UTC, DenomikoN commented on 4_ASP.NET_CORE/task1/task1WebAPI/task1WebAPI/Controllers/ValuesController.cs
> +                return Ok(new SumModel { A = (int)model.A, B =(int)model.B, Sum = (int)(model.A + model.B) });
1. Лучше сохранить в преременную, так проще считать
2. По нормальному, сложение это бизнесслогика и её желательно выносить в отдельные классы

2018-08-14 13:33 UTC, DenomikoN commented on 4_ASP.NET_CORE/task2/task2WebAPI/task2WebAPI/Services/StarsService.cs
> +                var client = new RestClient(currentUrl);
Нет необходимости создавать новый клиент на каждый запрос, ведь он всегда подключается к одному и тому же URL - вынеси в конструктор

2018-08-14 13:33 UTC, DenomikoN commented on 4_ASP.NET_CORE/task2/task2WebAPI/task2WebAPI/Services/StarsService.cs
> +                string currentUrl = url;
Зачем?)

2018-08-14 13:33 UTC, DenomikoN commented on 4_ASP.NET_CORE/task2/task2WebAPI/task2WebAPI/Services/StarsService.cs
> +                    starsOnePage =  JsonConvert.DeserializeObject<StarsResultWithNext>(responseStarsList.Task.Result);
RestSрarp умеет десереализовать сам, используй типзированный Execute<> и ExecuteAsync<>

2018-08-14 13:33 UTC, DenomikoN commented on 4_ASP.NET_CORE/task2/task2WebAPI/task2WebAPI/Services/StarsService.cs
> +        public async Task<StarsResult> GetAllStarsAsync()
В этом методе нет вызовов с await, в данном виде он не асинхронный

2018-08-14 13:33 UTC, DenomikoN commented on 4_ASP.NET_CORE/task2/task2WebAPI/task2WebAPI/Services/StarsService.cs
> +                    var responseStarsList = new TaskCompletionSource<string>();
TCS не нужен - просто дожидайся выполнения ExecuteAsync

2018-08-14 13:33 UTC, DenomikoN commented on 4_ASP.NET_CORE/task2/task2WebAPI/task2WebAPI/Services/StarsService.cs
> +                    for (int j = 0; j < starsOnePage.Results.Count; j++)
Вынеси в приватный метод

2018-08-14 13:33 UTC, DenomikoN commented on 4_ASP.NET_CORE/task2/task2WebAPI/task2WebAPI/Services/StarsService.cs
> +                    if (currentUrl != null) client = new RestClient(currentUrl);
Желательно разобрать URL и достать из него путь к ресурсу - к сл странице и переиспользовать RestClient

2018-08-14 13:33 UTC, DenomikoN commented on 4_ASP.NET_CORE/task2/task2WebAPI/task2WebAPI/Startup.cs
> +            services.AddTransient<IStarsService, StarsService>();
В данном случае должен быть AsSingleton - потом расскажи мне почему

2018-08-14 13:33 UTC, DenomikoN commented on 4_ASP.NET_CORE/task2/task2WebAPI/task2WebAPI/Services/StarsService.cs
> +                result = JsonConvert.DeserializeObject<StarsResult>(responseStarsList.Task.Result);
Тебе не нужно думать о десериализации

2018-08-14 13:33 UTC, DenomikoN commented on 4_ASP.NET_CORE/task2/task2WebAPI/task2WebAPI/Services/StarsService.cs
> +        public async Task<StarsResult> GetStarsAsync()
Всё ещё не асинхронный =)

2018-08-15 10:04 UTC, closed without merging

2018-08-16 08:20 UTC, lizaveta56 commented on 4_ASP.NET_CORE/task2/task2WebAPI/task2WebAPI/Startup.cs
> +            services.AddTransient<IStarsService, StarsService>();
Cannot consume scoped service 'AutoMapper.IMapper' from singleton 'task2WebAPI.Services.IStarsService'.

2018-08-16 08:21 UTC, lizaveta56 commented on 4_ASP.NET_CORE/task2/task2WebAPI/task2WebAPI/Services/StarsService.cs
> +                string currentUrl = url;
Не помню уже, но пересоздавая клиент так было проще работать. Убрала.

2018-08-16 08:31 UTC, Liza123-321 commented on 4_ASP.NET_CORE/task2/task2WebAPI/task2WebAPI/Services/StarsService.cs
> +                    starsOnePage =  JsonConvert.DeserializeObject<StarsResultWithNext>(responseStarsList.Task.Result);
Использовала GetTaskAsync<> и  Execute<>