Develop netcore task3
Liza123-321/iTechLab18-lizaveta.kaliaha pull request #11
Opened 2018-08-13 13:40 UTC by Liza123-321

2018-08-14 14:28 UTC, DenomikoN requested changes
Привет, ещё не запускал, пока несколько общих замечаний

2018-08-14 14:28 UTC, DenomikoN commented on 4_ASP.NET_CORE/task3/task3WebAPI/task3WebAPI/Logger/FileLogger.cs
> +    public class FileLogger : ILogger
Хорошо, но лучше использовать существующие библиотеки, например log4net
Там очень много тонких моментов связанных с синхронизацией и блокировкой файла

2018-08-14 14:28 UTC, DenomikoN commented on 4_ASP.NET_CORE/task3/task3WebAPI/task3WebAPI/Logger/FileLogger.cs
> +                lock (_lock)
хорошо +

2018-08-14 14:28 UTC, DenomikoN commented on 4_ASP.NET_CORE/task3/task3WebAPI/task3WebAPI/Services/FilmsService.cs
> +            if (!db.Films.Any())
Перенести в инициализацию базы в миграциях

2018-08-14 14:28 UTC, DenomikoN commented on 4_ASP.NET_CORE/task3/task3WebAPI/task3WebAPI/Services/FilmsService.cs
> +            }
валидация модели?

2018-08-14 14:28 UTC, DenomikoN commented on 4_ASP.NET_CORE/task3/task3WebAPI/task3WebAPI/Services/FilmsService.cs
> +            FilmModel film = db.Films.FirstOrDefault(x => x.Id == id);
Опять же тут бизнесс логика, лучше вынести в класс-сервис который будет инжектаться в контроллер (бонусное задание будет - UnitTest'ы и там будет намного проще с отдельным сервис-классом)

2018-08-14 14:28 UTC, DenomikoN commented on 4_ASP.NET_CORE/task3/task3WebAPI/task3WebAPI/Startup.cs
> +            services.AddTransient<IFilmsService, FilmsService>();
Почему именно такой Lifecycle?

2018-08-14 14:28 UTC, DenomikoN commented on 4_ASP.NET_CORE/task3/task3WebAPI/task3WebAPI/Startup.cs
> +            var logger = loggerFactory.CreateLogger("FileLogger");
Что дальше с этим экземпляром?

2018-08-14 14:28 UTC, DenomikoN commented on 4_ASP.NET_CORE/task3/task3WebAPI/task3WebAPI/Controllers/FilmsController.cs
> +    [ServiceFilter(typeof(LogActionAttribute))]
Зарегистируй его пожалуйста глобально

2018-08-15 11:49 UTC, closed without merging

2018-08-16 08:46 UTC, Liza123-321 commented on 4_ASP.NET_CORE/task3/task3WebAPI/task3WebAPI/Services/FilmsService.cs
> +            }
Удалила. Было до добавления аттрибутов в модель.

2018-08-16 08:47 UTC, Liza123-321 commented on 4_ASP.NET_CORE/task3/task3WebAPI/task3WebAPI/Services/FilmsService.cs
> +            FilmModel film = db.Films.FirstOrDefault(x => x.Id == id);
Это вынести в отдельный сервис или пойдет в отдельный метод в этом же сервисе?

2018-08-16 08:49 UTC, Liza123-321 commented on 4_ASP.NET_CORE/task3/task3WebAPI/task3WebAPI/Startup.cs
> +            services.AddTransient<IFilmsService, FilmsService>();
Исправила логгер на Singleton

2018-08-16 08:50 UTC, Liza123-321 commented on 4_ASP.NET_CORE/task3/task3WebAPI/task3WebAPI/Startup.cs
> +            var logger = loggerFactory.CreateLogger("FileLogger");
Ничего, удалила. Когда разбиралась тестила отправку запроса и логгирование, забыла удалить.