Develop netcore task1-2 fix
Liza123-321/iTechLab18-lizaveta.kaliaha pull request #12
Opened 2018-08-15 10:04 UTC by Liza123-321

2018-08-15 14:03 UTC, DenomikoN requested changes
Ты где-т опотеряла половину предыдущих комментариев. Плюс обрати внимание на именование методов
https://www.dofactory.com/reference/csharp-coding-standards

2018-08-15 14:03 UTC, DenomikoN commented on 4_ASP.NET_CORE/task1/task1WebAPI/task1WebAPI/Controllers/ValuesController.cs
> +                int sum = _sumService.sum((int)model.A,(int) model.B);
Сервис может принимать и возвращать DTO

2018-08-15 14:03 UTC, DenomikoN commented on 4_ASP.NET_CORE/task1/task1WebAPI/task1WebAPI/Startup.cs
> +            services.AddTransient<ISumService, SumService>();
Почему Transient ?

2018-08-15 14:03 UTC, DenomikoN commented on 4_ASP.NET_CORE/task2/task2WebAPI/task2WebAPI/Services/StarsService.cs
> +                result.Count += starsOnePage.Results.Count;
А он не равен result.Results.Count() ?

2018-08-15 14:03 UTC, DenomikoN commented on 4_ASP.NET_CORE/task2/task2WebAPI/task2WebAPI/Services/StarsService.cs
> +                for (int j = 0; j < starsOnePage.Results.Count; j++)
Один и тот же цикл - добавь в setIndex параметр (int startIndex=0) и используй тут

2018-08-15 14:03 UTC, DenomikoN commented on 4_ASP.NET_CORE/task2/task2WebAPI/task2WebAPI/Services/StarsService.cs
> +            this._restRequest= new RestRequest(Method.GET);
Запрос нужно каждый раз создавать

2018-08-15 14:03 UTC, DenomikoN commented on 4_ASP.NET_CORE/task2/task2WebAPI/task2WebAPI/Services/StarsService.cs
> +                if (starsOnePage.Next != null) client = new RestClient(starsOnePage.Next);
опять пересоздание клиента

2018-08-16 08:17 UTC, Liza123-321 commented on 4_ASP.NET_CORE/task1/task1WebAPI/task1WebAPI/Startup.cs
> +            services.AddTransient<ISumService, SumService>();
Исправила. Тут он только потому, что до этого я не разбиралась с другими.

2018-08-16 08:27 UTC, Liza123-321 commented on 4_ASP.NET_CORE/task2/task2WebAPI/task2WebAPI/Services/StarsService.cs
> +                result.Count += starsOnePage.Results.Count;
Равен. Исправила.

2018-08-16 08:27 UTC, Liza123-321 commented on 4_ASP.NET_CORE/task2/task2WebAPI/task2WebAPI/Services/StarsService.cs
> +                for (int j = 0; j < starsOnePage.Results.Count; j++)
Не знаю зачем,но я просто сделала индексирование уже по готову объекту из 37 элментов.

2018-08-16 08:35 UTC, closed without merging