Develop netcore task3 fix pull 11
Liza123-321/iTechLab18-lizaveta.kaliaha pull request #13
Opened 2018-08-15 11:50 UTC by Liza123-321

2018-08-15 13:08 UTC, DenomikoN requested changes

2018-08-15 13:08 UTC, DenomikoN commented on 4_ASP.NET_CORE/task3/task3WebAPI/task3WebAPI/Controllers/FilmsController.cs
> +        public async Task<ActionResult<IEnumerable<FilmModel>>> Get()
Попробуй просто `Task<IEnumerable<FilmModel>>`

2018-08-15 13:08 UTC, DenomikoN commented on 4_ASP.NET_CORE/task3/task3WebAPI/task3WebAPI/Services/IFilmsService.cs
> +        Task<FilmModel> createFilm(FilmModel film);
Именование

2018-08-15 13:08 UTC, DenomikoN commented on 4_ASP.NET_CORE/task3/task3WebAPI/task3WebAPI/Context/FilmsContextInit.cs
> +        {
Вот тут описано как это настраивается
http://www.entityframeworktutorial.net/code-first/seed-database-in-code-first.aspx

2018-08-15 14:04 UTC, DenomikoN commented on 4_ASP.NET_CORE/task3/task3WebAPI/task3WebAPI/Context/FilmsContextInit.cs
> +        {
Тут старые комментарии, можешь ответить или задать вопрос под каждым.

2018-08-15 14:04 UTC, DenomikoN commented on 4_ASP.NET_CORE/task3/task3WebAPI/task3WebAPI/Context/FilmsContextInit.cs
> +        {
https://github.com/Liza123-321/iTechLab18-lizaveta.kaliaha/pull/11

2018-08-16 08:43 UTC, Liza123-321 commented on 4_ASP.NET_CORE/task3/task3WebAPI/task3WebAPI/Controllers/FilmsController.cs
> +        public async Task<ActionResult<IEnumerable<FilmModel>>> Get()
Исправила, не помню зачем я это вообще так написала

2018-08-16 11:28 UTC, closed without merging